env:
  es2021: true
  node: true
extends:
  - '@react-native-community'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - 'simple-import-sort'
rules:
  'no-duplicate-imports':
    - error
    - includeExports: true
  'no-shadow': off
  'react-hooks/exhaustive-deps': off
  'semi': off
  'simple-import-sort/imports': error
  'sort-keys': error
